  <div id="fileHeader">
    <h1>error_generator.rb</h1>
    <table class="header-table">
    <tr class="top-aligned-row">
      <td><strong>Path:</strong></td>
      <td>lib/spec/mocks/error_generator.rb</td>
    </tr>
    <tr class="top-aligned-row">
      <td><strong>Last Update:</strong></td>
      <td>Mon Oct 12 14:57:53 +0200 2009</td>
    </tr>
    </table>
  </div>
 <!-- banner header -->

  <div id="bodyContent" >
    <h2>Source Code</h2>
    <pre>module Spec
  module Mocks
    class ErrorGenerator
      attr_writer :opts
      
      def initialize(target, name, options={})
        @declared_as = options[:__declared_as] || 'Mock'
        @target = target
        @name = name
      end
      
      def opts
        @opts ||= {}
      end

      def raise_unexpected_message_error(sym, *args)
        __raise &quot;#{intro} received unexpected message :#{sym}#{arg_message(*args)}&quot;
      end
      
      def raise_unexpected_message_args_error(expectation, *args)
        expected_args = format_args(*expectation.expected_args)
        actual_args = args.empty? ? &quot;(no args)&quot; : format_args(*args)
        __raise &quot;#{intro} received #{expectation.sym.inspect} with unexpected arguments\n  expected: #{expected_args}\n       got: #{actual_args}&quot;
      end
      
      def raise_expectation_error(sym, expected_received_count, actual_received_count, *args)
        __raise &quot;#{intro} expected :#{sym}#{arg_message(*args)} #{count_message(expected_received_count)}, but received it #{count_message(actual_received_count)}&quot;
      end
      
      def raise_out_of_order_error(sym)
        __raise &quot;#{intro} received :#{sym} out of order&quot;
      end
      
      def raise_block_failed_error(sym, detail)
        __raise &quot;#{intro} received :#{sym} but passed block failed with: #{detail}&quot;
      end
      
      def raise_missing_block_error(args_to_yield)
        __raise &quot;#{intro} asked to yield |#{arg_list(*args_to_yield)}| but no block was passed&quot;
      end
      
      def raise_wrong_arity_error(args_to_yield, arity)
        __raise &quot;#{intro} yielded |#{arg_list(*args_to_yield)}| to block with arity of #{arity}&quot;
      end
      
    private

      def intro
        if @name
          &quot;#{@declared_as} #{@name.inspect}&quot;
        elsif Mock === @target
          @declared_as
        elsif Class === @target
          &quot;&lt;#{@target.inspect} (class)&gt;&quot;
        elsif @target
          @target
        else
          &quot;nil&quot;
        end
      end
      
      def __raise(message)
        message = opts[:message] unless opts[:message].nil?
        Kernel::raise(Spec::Mocks::MockExpectationError, message)
      end
      
      def arg_message(*args)
        &quot; with &quot; + format_args(*args)
      end
      
      def format_args(*args)
        args.empty? ? &quot;(no args)&quot; : &quot;(&quot; + arg_list(*args) + &quot;)&quot;
      end

      def arg_list(*args)
        args.collect {|arg| arg.respond_to?(:description) ? arg.description : arg.inspect}.join(&quot;, &quot;)
      end
      
      def count_message(count)
        return &quot;at least #{pretty_print(count.abs)}&quot; if count &lt; 0
        return pretty_print(count)
      end

      def pretty_print(count)
        return &quot;once&quot; if count == 1
        return &quot;twice&quot; if count == 2
        return &quot;#{count} times&quot;
      end

    end
  end
end
</pre>
    </div>